// Fixture data shaped exactly like the published-map data contract (spec §6).
// SYNTHETIC content, real shape: swap for golden-corpus data without touching components.

export const MAP_VERSION = 41;
export const THIN_OBSERVATION_FLOOR = 3;
export const BUILDS = ["8.90", "8.98", "8.104", "8.112"];
export const FRAME_LINE = "staging · test tenancy · default experience";

export const FACETS = {
  cohort: ["new"],
  locale: ["en-US", "de-DE"],
  market: ["US", "DE"],
};

export const LANES = [
  {id: "meals-android", container: "Meals", platform: "Android", surface: "app",
   description: "Primary consumer meals app on Android."},
  {id: "meals-ios", container: "Meals", platform: "iOS", surface: "app",
   description: "Primary consumer meals app on iOS."},
  {id: "trips-android", container: "Trips", platform: "Android", surface: "app",
   description: "Trips app on Android; meal surfaces can embed here."},
  {id: "trips-ios", container: "Trips", platform: "iOS", surface: "app",
   description: "Trips app on iOS; meal surfaces can embed here."},
  {id: "bazaar-android", container: "Bazaar", platform: "Android", surface: "app",
   description: "Partner white-label container on Android."},
];

export const JOURNEYS = [
  {id: "onboarding", label: "Onboarding", coverageRowId: "cov-onb", team: "Consumer Identity",
   description: "First run: from install to a usable Home.",
   phases: ["Launch", "Sign up", "Verify", "Permissions", "Setup", "Home"]},
  {id: "checkout", label: "Checkout", coverageRowId: "cov-chk", team: "Payments",
   description: "From cart to placed order.",
   phases: ["Cart", "Address", "Payment", "Review", "Confirmation"]},
  {id: "search", label: "Search & Browse", coverageRowId: "cov-sb", team: "Growth",
   description: "Finding stores and items: browse, search, storefront.",
   phases: ["Entry", "Browse", "Search", "Item"]},
  {id: "tracking", label: "Order Tracking", coverageRowId: "cov-ot", team: "Presentation",
   description: "The live order: prep, courier, handoff.",
   phases: ["Placed", "Preparing", "Courier", "Delivered"]},
  {id: "account", label: "Account", coverageRowId: "cov-ac", team: "Consumer Identity",
   description: "Profile, payments, preferences, and help.",
   phases: ["Profile", "Payments", "Preferences", "Support"]},
];

const S = (key, kind, label, journeyId, phase, joinStep, suggestedLabel = null) => ({
  key, kind, label, journeyId, phase, joinStep, suggestedLabel,
  derivedLabel: label ?? `${phase} screen`,
});

export const SCREENS = Object.fromEntries([
  S("onb/welcome#a3f2", "SCREEN", "Welcome", "onboarding", "Launch", "onb.welcome"),
  S("onb/phone#77c1", "SCREEN", "Phone entry", "onboarding", "Sign up", "onb.phone"),
  S("ovl/sms-consent#19bd", "OVERLAY", "SMS consent", "onboarding", "Sign up", "onb.sms"),
  S("onb/verify-1#08aa", "SCREEN", null, "onboarding", "Verify", "onb.otp", "OTP entry"),
  S("ovl/otp-toast#d0d0", "OVERLAY", "Code didn't arrive", "onboarding", "Verify", "onb.otp.err"),
  S("onb/notif-perm#5b21", "SCREEN", "Notifications permission", "onboarding", "Permissions", "onb.perm.notif"),
  S("ovl/eu-consent#4c19", "OVERLAY", "EU data consent", "onboarding", "Permissions", "onb.perm.eu"),
  S("onb/marketing-optin#b7e0", "SCREEN", "Marketing opt-in", "onboarding", "Permissions", "onb.perm.mkt"),
  S("onb/tipping-intro#20fe", "SCREEN", "Tipping intro", "onboarding", "Setup", "onb.setup.tip"),
  S("onb/address#91aa", "SCREEN", "Address entry", "onboarding", "Setup", "onb.setup.addr"),
  S("ovl/loc-tooltip#3e77", "OVERLAY", "Location tip", "onboarding", "Home", "onb.home.tip"),
  S("ovl/whats-new#66d2", "OVERLAY", "What's new", "onboarding", "Home", "onb.home.new"),
  S("onb/home#f00d", "SCREEN", "Home feed", "onboarding", "Home", "onb.home"),
  S("chk/cart#11ab", "SCREEN", "Cart", "checkout", "Cart", "chk.cart"),
  S("chk/pay#22bc", "SCREEN", "Payment", "checkout", "Payment", "chk.pay"),
  // Search & Browse
  S("sb/home-entry#c101", "SCREEN", "Home feed entry", "search", "Entry", "sb.entry"),
  S("sb/category-grid#c102", "SCREEN", "Category grid", "search", "Browse", "sb.cats"),
  S("sb/store-list#c103", "SCREEN", "Store list", "search", "Browse", "sb.stores"),
  S("ovl/filter-sheet#c104", "OVERLAY", "Filter sheet", "search", "Browse", "sb.filters"),
  S("ovl/promo-banner#c105", "OVERLAY", "Promo banner", "search", "Browse", "sb.promo"),
  S("sb/search-entry#c106", "SCREEN", "Search", "search", "Search", "sb.search"),
  S("sb/search-results#c107", "SCREEN", "Search results", "search", "Search", "sb.results"),
  S("sb/store-front#c108", "SCREEN", null, "search", "Item", "sb.storefront", "Storefront"),
  S("sb/item-detail#c109", "SCREEN", "Item detail", "search", "Item", "sb.item"),
  S("ovl/item-customize#c110", "OVERLAY", "Item customization", "search", "Item", "sb.customize"),
  S("sb/cart-preview#c111", "SCREEN", "Cart preview", "search", "Item", "sb.cartpeek"),
  // Order Tracking
  S("ot/order-confirmed#d201", "SCREEN", "Order confirmed", "tracking", "Placed", "ot.confirmed"),
  S("ot/prep-status#d202", "SCREEN", "Preparing status", "tracking", "Preparing", "ot.prep"),
  S("ovl/eta-updated#d203", "OVERLAY", "ETA updated", "tracking", "Preparing", "ot.eta"),
  S("ot/courier-map#d204", "SCREEN", "Courier map", "tracking", "Courier", "ot.map"),
  S("ovl/courier-msg#d205", "OVERLAY", "Courier message", "tracking", "Courier", "ot.msg"),
  S("ot/delivery-photo#d206", "SCREEN", "Delivery photo", "tracking", "Delivered", "ot.photo"),
  S("ot/rate-order#d207", "SCREEN", null, "tracking", "Delivered", "ot.rate", "Order rating"),
  S("ovl/tip-prompt#d208", "OVERLAY", "Tip prompt", "tracking", "Delivered", "ot.tip"),
  // Account
  S("ac/profile#e301", "SCREEN", "Profile", "account", "Profile", "ac.profile"),
  S("ac/edit-profile#e302", "SCREEN", "Edit profile", "account", "Profile", "ac.edit"),
  S("ac/payment-methods#e303", "SCREEN", "Payment methods", "account", "Payments", "ac.payments"),
  S("ovl/add-card#e304", "OVERLAY", "Add card", "account", "Payments", "ac.addcard"),
  S("ac/preferences#e305", "SCREEN", "Preferences", "account", "Preferences", "ac.prefs"),
  S("ovl/notif-settings#e306", "OVERLAY", null, "account", "Preferences", "ac.notifs", "Notification settings"),
  S("ac/support-hub#e307", "SCREEN", "Support hub", "account", "Support", "ac.support"),
  S("ovl/chat-launcher#e308", "OVERLAY", "Support chat launcher", "account", "Support", "ac.chat"),
  S("ac/help-article#e309", "SCREEN", "Help article", "account", "Support", "ac.help"),
].map((s) => [s.key, s]));

export const EDGES = [
  {from: "onb/welcome#a3f2", to: "onb/phone#77c1", role: "FORWARD", traversable: true},
  {from: "onb/phone#77c1", to: "ovl/sms-consent#19bd", role: "SYSTEM", traversable: true},
  {from: "ovl/sms-consent#19bd", to: "onb/verify-1#08aa", role: "FORWARD", traversable: true},
  {from: "onb/verify-1#08aa", to: "ovl/otp-toast#d0d0", role: "SYSTEM", traversable: false},
  {from: "onb/verify-1#08aa", to: "onb/notif-perm#5b21", role: "FORWARD", traversable: true},
  {from: "onb/notif-perm#5b21", to: "ovl/eu-consent#4c19", role: "SYSTEM", traversable: true},
  {from: "ovl/eu-consent#4c19", to: "onb/marketing-optin#b7e0", role: "FORWARD", traversable: true},
  {from: "onb/marketing-optin#b7e0", to: "onb/address#91aa", role: "FORWARD", traversable: true},
  {from: "onb/notif-perm#5b21", to: "onb/tipping-intro#20fe", role: "FORWARD", traversable: true},
  {from: "onb/tipping-intro#20fe", to: "onb/address#91aa", role: "FORWARD", traversable: true},
  {from: "onb/address#91aa", to: "onb/home#f00d", role: "FORWARD", traversable: true},
  {from: "sb/home-entry#c101", to: "sb/category-grid#c102", role: "FORWARD", traversable: true},
  {from: "sb/category-grid#c102", to: "sb/store-list#c103", role: "FORWARD", traversable: true},
  {from: "sb/store-list#c103", to: "ovl/filter-sheet#c104", role: "SYSTEM", traversable: true},
  {from: "sb/store-list#c103", to: "ovl/promo-banner#c105", role: "SYSTEM", traversable: false},
  {from: "sb/store-list#c103", to: "sb/search-entry#c106", role: "FORWARD", traversable: true},
  {from: "sb/search-entry#c106", to: "sb/search-results#c107", role: "FORWARD", traversable: true},
  {from: "sb/search-results#c107", to: "sb/store-front#c108", role: "FORWARD", traversable: true},
  {from: "sb/store-front#c108", to: "sb/item-detail#c109", role: "FORWARD", traversable: true},
  {from: "sb/item-detail#c109", to: "ovl/item-customize#c110", role: "SYSTEM", traversable: true},
  {from: "ovl/item-customize#c110", to: "sb/cart-preview#c111", role: "FORWARD", traversable: true},
  {from: "ot/order-confirmed#d201", to: "ot/prep-status#d202", role: "FORWARD", traversable: true},
  {from: "ot/prep-status#d202", to: "ovl/eta-updated#d203", role: "SYSTEM", traversable: false},
  {from: "ot/prep-status#d202", to: "ot/courier-map#d204", role: "FORWARD", traversable: true},
  {from: "ot/courier-map#d204", to: "ovl/courier-msg#d205", role: "SYSTEM", traversable: true},
  {from: "ot/courier-map#d204", to: "ot/delivery-photo#d206", role: "FORWARD", traversable: true},
  {from: "ot/delivery-photo#d206", to: "ot/rate-order#d207", role: "FORWARD", traversable: true},
  {from: "ot/rate-order#d207", to: "ovl/tip-prompt#d208", role: "SYSTEM", traversable: true},
  {from: "ac/profile#e301", to: "ac/edit-profile#e302", role: "FORWARD", traversable: true},
  {from: "ac/profile#e301", to: "ac/payment-methods#e303", role: "FORWARD", traversable: true},
  {from: "ac/payment-methods#e303", to: "ovl/add-card#e304", role: "SYSTEM", traversable: true},
  {from: "ac/payment-methods#e303", to: "ac/preferences#e305", role: "FORWARD", traversable: true},
  {from: "ac/preferences#e305", to: "ovl/notif-settings#e306", role: "SYSTEM", traversable: true},
  {from: "ac/preferences#e305", to: "ac/support-hub#e307", role: "FORWARD", traversable: true},
  {from: "ac/support-hub#e307", to: "ovl/chat-launcher#e308", role: "SYSTEM", traversable: true},
  {from: "ac/support-hub#e307", to: "ac/help-article#e309", role: "FORWARD", traversable: true},
];

const walkDE = [
  {stack: ["onb/welcome#a3f2"], variants: ["POPULATED"], occluded: []},
  {stack: ["onb/phone#77c1"], variants: ["POPULATED", "ERROR"], occluded: []},
  {stack: ["ovl/sms-consent#19bd", "onb/phone#77c1"], variants: ["POPULATED"], occluded: []},
  {stack: ["onb/verify-1#08aa"], variants: ["POPULATED", "LOADING"], occluded: []},
  {stack: ["onb/notif-perm#5b21"], variants: ["POPULATED"], occluded: []},
  {stack: ["ovl/eu-consent#4c19", "onb/notif-perm#5b21"], variants: ["POPULATED"], occluded: []},
  {stack: ["onb/marketing-optin#b7e0"], variants: ["POPULATED"], occluded: []},
  {stack: ["onb/address#91aa"], variants: ["POPULATED", "ERROR"], occluded: []},
  {stack: ["ovl/whats-new#66d2", "ovl/loc-tooltip#3e77", "onb/home#f00d"],
   variants: ["POPULATED"], occluded: ["ovl/loc-tooltip#3e77"]},
];

const walkUS = [
  {stack: ["onb/welcome#a3f2"], variants: ["POPULATED"], occluded: []},
  {stack: ["onb/phone#77c1"], variants: ["POPULATED"], occluded: []},
  {stack: ["ovl/sms-consent#19bd", "onb/phone#77c1"], variants: ["POPULATED"], occluded: []},
  {stack: ["onb/verify-1#08aa"], variants: ["POPULATED"], occluded: []},
  {stack: ["onb/notif-perm#5b21"], variants: ["POPULATED"], occluded: []},
  {stack: ["onb/tipping-intro#20fe"], variants: ["POPULATED"], occluded: []},
  {stack: ["onb/address#91aa"], variants: ["POPULATED"], occluded: []},
  {stack: ["onb/home#f00d"], variants: ["POPULATED"], occluded: []},
];

const walkSearch = [
  {stack: ["sb/home-entry#c101"], variants: ["POPULATED"], occluded: []},
  {stack: ["sb/category-grid#c102"], variants: ["POPULATED"], occluded: []},
  {stack: ["sb/store-list#c103"], variants: ["POPULATED", "EMPTY"], occluded: []},
  {stack: ["ovl/filter-sheet#c104", "sb/store-list#c103"], variants: ["POPULATED"], occluded: []},
  {stack: ["sb/search-entry#c106"], variants: ["POPULATED", "EMPTY"], occluded: []},
  {stack: ["sb/search-results#c107"], variants: ["POPULATED", "ERROR"], occluded: []},
  {stack: ["sb/store-front#c108"], variants: ["POPULATED"], occluded: []},
  {stack: ["sb/item-detail#c109"], variants: ["POPULATED", "LOADING"], occluded: []},
  {stack: ["ovl/item-customize#c110", "sb/item-detail#c109"], variants: ["POPULATED"], occluded: []},
  {stack: ["sb/cart-preview#c111"], variants: ["POPULATED"], occluded: []},
];

const walkTracking = [
  {stack: ["ot/order-confirmed#d201"], variants: ["POPULATED"], occluded: []},
  {stack: ["ot/prep-status#d202"], variants: ["POPULATED"], occluded: []},
  {stack: ["ot/courier-map#d204"], variants: ["POPULATED", "LOADING"], occluded: []},
  {stack: ["ovl/courier-msg#d205", "ot/courier-map#d204"], variants: ["POPULATED"], occluded: []},
  {stack: ["ot/delivery-photo#d206"], variants: ["POPULATED"], occluded: []},
  {stack: ["ot/rate-order#d207"], variants: ["POPULATED"], occluded: []},
  {stack: ["ovl/tip-prompt#d208", "ot/rate-order#d207"], variants: ["POPULATED"], occluded: []},
];

const walkAccount = [
  {stack: ["ac/profile#e301"], variants: ["POPULATED"], occluded: []},
  {stack: ["ac/edit-profile#e302"], variants: ["POPULATED"], occluded: []},
  {stack: ["ac/payment-methods#e303"], variants: ["POPULATED", "EMPTY"], occluded: []},
  {stack: ["ovl/add-card#e304", "ac/payment-methods#e303"], variants: ["POPULATED"], occluded: []},
  {stack: ["ac/preferences#e305"], variants: ["POPULATED"], occluded: []},
  {stack: ["ovl/notif-settings#e306", "ac/preferences#e305"], variants: ["POPULATED"], occluded: []},
  {stack: ["ac/support-hub#e307"], variants: ["POPULATED"], occluded: []},
  {stack: ["ovl/chat-launcher#e308", "ac/support-hub#e307"], variants: ["POPULATED"], occluded: []},
  {stack: ["ac/help-article#e309"], variants: ["POPULATED", "LOADING"], occluded: []},
];

export const OBSERVATIONS = [
  {lane: "meals-android", market: "DE", locale: "de-DE", cohort: "new", build: "8.112",
   journey: "onboarding", observedAt: "2026-08-21T09:10:00Z", runId: "run-4411", obsCount: 7, walk: walkDE},
  {lane: "meals-android", market: "US", locale: "en-US", cohort: "new", build: "8.112",
   journey: "onboarding", observedAt: "2026-08-21T09:42:00Z", runId: "run-4412", obsCount: 6, walk: walkUS},
  {lane: "meals-android", market: "US", locale: "en-US", cohort: "new", build: "8.98",
   journey: "onboarding", observedAt: "2026-07-20T11:00:00Z", runId: "run-3980", obsCount: 5,
   walk: walkUS.slice(0, 7)},
  {lane: "meals-android", market: "US", locale: "en-US", cohort: "new", build: "8.112",
   journey: "checkout", observedAt: "2026-08-21T10:05:00Z", runId: "run-4413", obsCount: 5,
   walk: [
     {stack: ["chk/cart#11ab"], variants: ["POPULATED", "EMPTY"], occluded: []},
     {stack: ["chk/pay#22bc"], variants: ["POPULATED"], occluded: []},
   ]},
  {lane: "meals-ios", market: "US", locale: "en-US", cohort: "new", build: "8.98",
   journey: "onboarding", observedAt: "2026-07-22T08:00:00Z", runId: "run-4001", obsCount: 4,
   walk: walkUS.slice(0, 8)},
  {lane: "meals-ios", market: "US", locale: "en-US", cohort: "new", build: "8.112",
   journey: "checkout", observedAt: "2026-08-20T16:20:00Z", runId: "run-4390", obsCount: 1,
   walk: [{stack: ["chk/cart#11ab"], variants: ["POPULATED"], occluded: []}]},
  {lane: "meals-android", market: "US", locale: "en-US", cohort: "new", build: "8.112",
   journey: "search", observedAt: "2026-08-21T11:00:00Z", runId: "run-4520", obsCount: 6, walk: walkSearch},
  {lane: "meals-android", market: "US", locale: "en-US", cohort: "new", build: "8.90",
   journey: "search", observedAt: "2026-06-14T10:00:00Z", runId: "run-3720", obsCount: 2,
   walk: walkSearch.slice(0, 6)},
  {lane: "meals-android", market: "US", locale: "en-US", cohort: "new", build: "8.112",
   journey: "tracking", observedAt: "2026-08-21T12:30:00Z", runId: "run-4531", obsCount: 4, walk: walkTracking},
  {lane: "meals-android", market: "US", locale: "en-US", cohort: "new", build: "8.104",
   journey: "tracking", observedAt: "2026-08-02T09:00:00Z", runId: "run-4210", obsCount: 3,
   walk: walkTracking.slice(0, 5)},
  {lane: "meals-android", market: "US", locale: "en-US", cohort: "new", build: "8.112",
   journey: "account", observedAt: "2026-08-21T14:10:00Z", runId: "run-4544", obsCount: 5, walk: walkAccount},
  {lane: "meals-ios", market: "US", locale: "en-US", cohort: "new", build: "8.104",
   journey: "account", observedAt: "2026-08-03T15:45:00Z", runId: "run-4215", obsCount: 3,
   walk: walkAccount.slice(0, 7)},
];

// ---------------------------------------------------------------------------
// Validation reports.
//
// A report is one agentic validation run over Given/When/Then requirements,
// executed per lane. Same synthetic-content / real-shape rule as the rest of
// this module: requirements cite frozen screen keys from SCREENS above, and
// jobs run in lanes from LANES, so a report is part of the map rather than a
// document sitting beside it.
// ---------------------------------------------------------------------------

export const REQUIREMENT_STATUSES = ["pass", "fail", "flaky", "review", "blocked",
  "skip", "running", "queued"];

/** Statuses that still count as a verdict rather than an absence of one. */
export const TERMINAL_STATUSES = ["pass", "fail", "flaky", "review"];

const rq = (id, status, dur, given, when, then, extra = {}) =>
  ({id, status, dur, given, when, then, screens: [], ...extra});

const APP_ARTIFACTS = [{label: "Session replay", icon: "filmstrip"},
  {label: "Agent transcript", icon: "file-text"}];

export const REPORTS = [
  {
    id: "1284",
    title: "Gate the tipping intro to US onboarding",
    repo: "northstar/meals-consumer",
    branch: "feat/tipping-gate-us",
    baseBranch: "main",
    commit: "8f3c2e1",
    pullRequest: "482",
    build: "8.112",
    trigger: "push",
    startedAt: "2026-08-22T14:32:00Z",
    finishedAt: "2026-08-22T14:48:04Z",
    duration: "16m 04s",
    evidenceRetentionDays: 90,
    classes: [
      {
        name: "App validation",
        jobs: [
          {
            id: "meals-android",
            name: "Meals · Android agentic validation",
            laneId: "meals-android",
            env: "Pixel 9 emulator · Android 15 · build 8.112",
            duration: "6m 12s",
            artifacts: APP_ARTIFACTS,
            requirements: [
              rq("VR-101", "pass", "1m 58s",
                "a new user in the US who has verified their phone",
                "they finish the permissions step",
                "the tipping intro is shown before address entry",
                {screens: ["onb/notif-perm#5b21", "onb/tipping-intro#20fe", "onb/address#91aa"]}),
              rq("VR-102", "fail", "2m 08s",
                "a new user in DE who has verified their phone",
                "they finish the permissions step",
                "the tipping intro is never shown and EU data consent is shown instead",
                {
                  screens: ["onb/notif-perm#5b21", "onb/tipping-intro#20fe", "ovl/eu-consent#4c19"],
                  message: "Assertion failed on step 4 — the tipping intro rendered for a DE user.",
                  expected: "EU data consent after Notifications permission; no tipping intro",
                  actual: "Tipping intro rendered 0.9s after Notifications permission",
                  steps: [
                    ["Installed b8.112 and seeded a new DE account", "pass"],
                    ["Set device locale de-DE and market DE", "pass"],
                    ["Completed phone entry and SMS consent", "pass"],
                    ["Reached Notifications permission — tipping intro appeared next", "fail"],
                  ],
                  logTitle: "Console log",
                  log: [
                    "14:36:02.114 [OnboardingPlan] market=DE locale=de-DE cohort=new",
                    "14:36:02.118 [OnboardingPlan] geo_gate=null — defaulting to eligible",
                    "14:36:03.542 [UI] presenting onb/tipping-intro#20fe",
                  ],
                  shot: "Capture — tipping intro over the DE onboarding spine",
                  artifacts: APP_ARTIFACTS.concat([{label: "Device log", icon: "terminal"}]),
                }),
              rq("VR-103", "pass", "58s",
                "a new user who has not verified their phone",
                "they reach the permissions step",
                "onboarding refuses to advance and returns to phone entry",
                {screens: ["onb/phone#77c1", "onb/verify-1#08aa"]}),
              rq("VR-104", "flaky", "3m 41s",
                "the network is throttled to a 3G profile",
                "the user lands on the home feed",
                "the home feed renders before any overlay is presented",
                {
                  screens: ["onb/home#f00d", "ovl/whats-new#66d2"],
                  note: "Attempt 1 failed — What's new blocked first contentful paint for 4.1s. Attempt 2 passed with the overlay deferred. Flagged flaky; does not block this merge.",
                }),
              rq("VR-105", "skip", "—",
                "a returning user who has already dismissed the tipping intro",
                "they reinstall and onboard again",
                "the tipping intro does not reappear",
                {note: "Skipped — no seeded account with a prior dismissal exists in this lane. Add a fixture to cover this requirement."}),
            ],
          },
          {
            id: "meals-ios",
            name: "Meals · iOS agentic validation",
            laneId: "meals-ios",
            env: "iPhone 16 Pro simulator · iOS 18.2 · build 8.112",
            duration: "5m 46s",
            artifacts: APP_ARTIFACTS,
            requirements: [
              rq("VR-106", "pass", "2m 02s",
                "a new user in the US who has verified their phone",
                "they finish the permissions step",
                "the tipping intro is shown before address entry",
                {screens: ["onb/tipping-intro#20fe", "onb/address#91aa"]}),
              rq("VR-107", "review", "2m 47s",
                "VoiceOver is enabled",
                "the tipping intro appears",
                "focus moves to the intro and its primary action is announced",
                {
                  screens: ["onb/tipping-intro#20fe"],
                  note: "The agent could not confirm announcement order — VoiceOver read the dismiss control before the primary action. A screen recording is attached; a human should judge whether this meets the requirement.",
                  artifacts: [{label: "Screen recording (0:41)", icon: "filmstrip"},
                    {label: "Agent transcript", icon: "file-text"}],
                }),
              rq("VR-108", "blocked", "—",
                "a new user in DE",
                "they finish the permissions step",
                "EU data consent is shown",
                {
                  screens: ["ovl/eu-consent#4c19"],
                  note: "Blocked — this lane has no observed DE walk to validate against. The map reports Meals · iOS onboarding as last observed on b8.98.",
                }),
            ],
          },
          {
            id: "bazaar-android",
            name: "Bazaar · Android agentic validation",
            laneId: "bazaar-android",
            env: "Pixel 7 emulator · Android 14 · build 8.112",
            duration: "2m 11s",
            artifacts: APP_ARTIFACTS,
            requirements: [
              rq("VR-109", "blocked", "—",
                "a new user in the partner container",
                "they finish the permissions step",
                "the tipping intro follows the host app's gate",
                {note: "Blocked — Bazaar · Android is not in the crawl set, so no walk exists to validate. Seed the lane before this requirement can run."}),
            ],
          },
        ],
      },
      {
        name: "Contract validation",
        jobs: [
          {
            id: "api",
            name: "Onboarding plan contract",
            laneId: null,
            env: "staging · onboarding-plan-svc v2.14.0 · 426 assertions",
            duration: "1m 47s",
            artifacts: [{label: "Request log", icon: "terminal"}],
            requirements: [
              rq("VR-110", "pass", "4s",
                "a new user with market US",
                "the client requests GET /v1/onboarding/plan",
                "the plan includes the tipping intro step"),
              rq("VR-111", "fail", "6s",
                "any client on contract v2",
                "an onboarding plan is returned",
                "every step carries the market it was gated on",
                {
                  message: 'Contract violation — required field "gated_on" is missing from the response.',
                  expected: 'gated_on: "market" present on every gated step',
                  actual: "Field absent in 240 of 240 sampled responses",
                  logTitle: "Response sample",
                  log: [
                    "GET /v1/onboarding/plan?market=DE → 200 (38ms)",
                    "{",
                    '  "step": "onb/tipping-intro#20fe",',
                    '  "position": 6',
                    "}",
                    'missing required field "gated_on" — contract v2 §3.2',
                  ],
                  artifacts: [{label: "Contract diff", icon: "code-compare"},
                    {label: "Response samples (240)", icon: "curly-brackets"}],
                }),
              rq("VR-112", "pass", "3s",
                "a new user with market DE",
                "the client requests GET /v1/onboarding/plan",
                "the plan omits the tipping intro step"),
              rq("VR-113", "pass", "11s",
                "the plan service is unavailable",
                "onboarding starts",
                "the client falls back to the last published plan and surfaces no error"),
              rq("VR-114", "pass", "2s",
                "the request is unauthenticated",
                "GET /v1/onboarding/plan is called",
                "the API returns 401 and no plan metadata"),
            ],
          },
        ],
      },
    ],
  },
  {
    id: "1281",
    title: "Split store list filters into a sheet",
    repo: "northstar/meals-consumer",
    branch: "feat/filter-sheet",
    baseBranch: "main",
    commit: "b41d90a",
    pullRequest: "478",
    build: "8.112",
    trigger: "push",
    startedAt: "2026-08-21T11:02:00Z",
    finishedAt: "2026-08-21T11:11:35Z",
    duration: "9m 35s",
    evidenceRetentionDays: 90,
    classes: [
      {
        name: "App validation",
        jobs: [
          {
            id: "meals-android",
            name: "Meals · Android agentic validation",
            laneId: "meals-android",
            env: "Pixel 9 emulator · Android 15 · build 8.112",
            duration: "9m 35s",
            artifacts: APP_ARTIFACTS,
            requirements: [
              rq("VR-090", "pass", "1m 12s",
                "a user browsing the store list",
                "they open filters",
                "the filter sheet is presented over the store list",
                {screens: ["sb/store-list#c103", "ovl/filter-sheet#c104"]}),
              rq("VR-091", "pass", "1m 30s",
                "the filter sheet is open",
                "the user applies a filter and dismisses the sheet",
                "the store list reflects the filter and the sheet does not reappear",
                {screens: ["ovl/filter-sheet#c104", "sb/store-list#c103"]}),
              rq("VR-092", "pass", "58s",
                "no store matches the applied filters",
                "the store list renders",
                "the empty state is shown with a control to clear filters",
                {screens: ["sb/store-list#c103"]}),
              rq("VR-093", "pass", "1m 04s",
                "the filter sheet is open",
                "the user presses back",
                "the sheet closes and no filter is applied",
                {screens: ["ovl/filter-sheet#c104"]}),
            ],
          },
        ],
      },
    ],
  },
  {
    id: "1286",
    title: "Add courier message overlay to order tracking",
    repo: "northstar/meals-consumer",
    branch: "feat/courier-message",
    baseBranch: "main",
    commit: "c7e1042",
    pullRequest: "486",
    build: "8.112",
    trigger: "push",
    startedAt: "2026-08-23T09:14:00Z",
    finishedAt: null,
    duration: "6m 02s elapsed",
    evidenceRetentionDays: 90,
    classes: [
      {
        name: "App validation",
        jobs: [
          {
            id: "meals-android",
            name: "Meals · Android agentic validation",
            laneId: "meals-android",
            env: "Pixel 9 emulator · Android 15 · build 8.112",
            duration: "6m 02s elapsed",
            artifacts: APP_ARTIFACTS,
            requirements: [
              rq("VR-131", "pass", "1m 26s",
                "an order is out for delivery",
                "the courier sends a message",
                "the courier message overlay is presented over the courier map",
                {screens: ["ot/courier-map#d204", "ovl/courier-msg#d205"]}),
              rq("VR-132", "running", "—",
                "the courier message overlay is visible",
                "the user dismisses it",
                "the courier map remains interactive and the message is marked read",
                {screens: ["ovl/courier-msg#d205", "ot/courier-map#d204"]}),
              rq("VR-133", "queued", "—",
                "the app is backgrounded when a message arrives",
                "the user reopens the app",
                "the overlay is presented once and only once",
                {screens: ["ovl/courier-msg#d205"]}),
              rq("VR-134", "queued", "—",
                "delivery has completed",
                "a late courier message arrives",
                "no overlay is presented over the delivery photo",
                {screens: ["ot/delivery-photo#d206", "ovl/courier-msg#d205"]}),
            ],
          },
        ],
      },
    ],
  },
];
